package eu.prisoscar.euler1.soluzioni;

import eu.prisoscar.euler1.algoritmi_trasversali.NumberSequences;

import java.util.List;

/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
 */
public class Prbl_45_TriangularPentagonalAndHexagonal {

    private static final int SUPPOSED_TARGET = 100_000;

    public static long getSolution(){
        long     solution = 0;
        List<Long> triangleNumbers = NumberSequences.triangleNumbersSequence(SUPPOSED_TARGET);
        List<Long> pentagonNumbers = NumberSequences.pentagonNumbersSequence(SUPPOSED_TARGET);
        List<Long> hexagonNumbers = NumberSequences.hexagonNumbersSequence(SUPPOSED_TARGET);
        for (int i = 285; i < SUPPOSED_TARGET; i++){
            if (pentagonNumbers.contains(triangleNumbers.get(i)) && hexagonNumbers.contains(triangleNumbers.get(i))){
                solution = triangleNumbers.get(i);
                break;
            }
        }
        return solution;
    }
}
